"""populate event_position

Revision ID: 115e3877bb2f
Revises: 8390eb5f83a9
Create Date: 2025-01-20 11:54:10.585984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '115e3877bb2f'
down_revision: Union[str, None] = '8390eb5f83a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        WITH ranked_events AS (
            SELECT id, 
                   row_number() OVER (PARTITION BY event_rink, competition_id ORDER BY id) AS event_position
            FROM events
        )
        UPDATE events e
        SET event_position = re.event_position
        FROM ranked_events re
        WHERE e.id = re.id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_position')
    # ### end Alembic commands ###
