"""change file_status enum

Revision ID: 314758b3689d
Revises: 502fee06b176
Create Date: 2025-02-08 10:56:01.497111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '314758b3689d'
down_revision: Union[str, None] = '502fee06b176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

file_status_enum = sa.Enum('STAGED', 'IN_PROGRESS', 'FINISHED', 'ABORTED', 'UPLOAD_ERROR', name ='file_status_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DROP TYPE IF EXISTS file_status_enum CASCADE")
    file_status_enum.create(op.get_bind())
    op.add_column("files", sa.Column('file_status', file_status_enum, nullable=False, server_default="FINISHED"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skates', 'skate_position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skates', 'footage_exceptions',
               existing_type=sa.Enum('SCRATCH', 'NO_VIDEO', 'NO_PHOTO', 'MULTIPLE_VIDEOS', name='footageexceptions'),
               type_=postgresql.ENUM('SCRATCH', 'NO_VIDEO', 'NO_PHOTO', 'MULTIPLE_VIDEOS', name='footage_exceptions_enum'),
               existing_nullable=True)
    op.add_column('files', sa.Column('file_status', postgresql.ENUM('staged', 'in progress', 'finished', 'aborted', 'upload error', name='file_status_enum'), server_default=sa.text("'finished'::file_status_enum"), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('creation_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.alter_column('files', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'event_position',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
