"""Changed skate position columns

Revision ID: 516fb37c0e42
Revises: 115e3877bb2f
Create Date: 2025-02-07 16:19:04.192218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '516fb37c0e42'
down_revision: Union[str, None] = '115e3877bb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skates', 'skate_position')
    op.add_column('skates', sa.Column('skate_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
