"""init

Revision ID: 5bb897a7e91d
Revises: 
Create Date: 2024-02-06 22:56:07.426255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb897a7e91d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_name', sa.String(length=60), nullable=False),
    sa.Column('competition_year', sa.Integer(), nullable=False),
    sa.Column('host_club', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('competition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'competition_id')
    op.drop_table('competitions')
    # ### end Alembic commands ###
