"""change position columns

Revision ID: 8390eb5f83a9
Revises: 3e25c5a0ede0
Create Date: 2025-01-20 11:31:00.554935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8390eb5f83a9'
down_revision: Union[str, None] = '3e25c5a0ede0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_position')
    op.add_column('events', sa.Column('event_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skates', sa.Column('skate_position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('skates', sa.Column('footage_exceptions', postgresql.ENUM('SCRATCH', 'NO_VIDEO', 'NO_PHOTO', 'MULTIPLE_VIDEOS', name='footage_exceptions_enum'), autoincrement=False, nullable=True))
    op.create_unique_constraint('skates_skate_position_key', 'skates', ['skate_position'])
    op.add_column('files', sa.Column('file_status', postgresql.ENUM('staged', 'in progress', 'finished', 'aborted', 'upload error', name='file_status_enum'), server_default=sa.text("'finished'::file_status_enum"), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('creation_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.alter_column('files', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('events_event_position_key', 'events', ['event_position'])
    # ### end Alembic commands ###
